#!/usr/bin/python
import os
import urllib2

replace='replace.me'

req = urllib2.Request(url="http://169.254.169.254/latest/meta-data/public-hostname")
f = urllib2.urlopen(req)
public_hostname = f.read()

# ToDo: Grab user specified dns entry (and more ...) here

os.system("perl -pi -e 's/%s/%s/g' /etc/apache2/sites-available/geonode" % (replace, public_hostname))
os.system("perl -pi -e 's/%s/%s/g' /var/www/geonode/wsgi/geonode/src/GeoNodePy/geonode/local_settings.py" % (replace, public_hostname))
